### ISSUE TITLE
Support DYLD_LIBRARY_PATH from parent env in `sdk::DDSEnv`

### ISSUE THREAD

**Issue by AndreyLebedev** [FairRootGroup/FairMQ#235] opened 2020-01-31 09:10 UTC
**Describe the bug**
Using of 
```
{
        // Equivalent to calling source DDS_env.sh
        fair::mq::sdk::DDSEnv env;
}
```
on macOS results in runtime error
```
dyld: Library not loaded: libboost_program_options.dylib
  Referenced from: /Users/andrey/DDS/3.1/bin/dds-user-defaults
  Reason: image not found
sh: line 4: 26838 Abort trap: 6           dds-user-defaults --ignore-default-sid -d -c "$HOME/.DDS/DDS.cfg"
```
The problem is that [here](https://github.com/FairRootGroup/FairMQ/blob/19ab8bba3b3c3d59db0e2e75b47dd3b7932421fe/fairmq/sdk/DDSEnvironment.cxx#L50-L65) you execute `dds-user-defaults` by calling `std::system` which internally calls hosts's shell with the parameter command. On macOS `DYLD_LIBRARY_PATH` which you set before in the code will not be propagated to the child shell.

**System information (please complete the following information):**
 - OS: MacOS 10.15.2
 - Compiler: Apple clang version 11.0.0 (clang-1100.0.33.17)
 - Environment: custom installation of DDS, FairMQ, ODC

**Comment by dennisklein** [comment] 2020-01-31 15:27
Can you pls show the output of `otool -l $(which dds-user-defaults)`?

I ask, because for me on a DDS master installation on macOS, the binary contains all the correct `RPATH` entries - so it should be able to find boost, e.g.:

```
alfaci at witmac007 in ~/DDS/install on master*$ otool -l bin/dds-user-defaults
bin/dds-user-defaults:
(...)
Load command 13
          cmd LC_LOAD_DYLIB
      cmdsize 64
         name @rpath/libboost_program_options.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 0.0.0
compatibility version 0.0.0
Load command 14
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libboost_system.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 0.0.0
compatibility version 0.0.0
Load command 15
          cmd LC_LOAD_DYLIB
      cmdsize 64
         name @rpath/libboost_filesystem.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 0.0.0
compatibility version 0.0.0
(...)
Load command 19
          cmd LC_RPATH
      cmdsize 48
         path /Users/alfaci/DDS/install/lib (offset 12)
Load command 20
          cmd LC_RPATH
      cmdsize 56
         path /Users/alfaci/fairsoft/fairmq_dev/lib (offset 12)
```

And one of the `RPATH` entries contains the boost libraries:

```
alfaci at witmac007 in ~/DDS/install on master*$ ls /Users/alfaci/fairsoft/fairmq_dev/lib/libboost_*.dylib
/Users/alfaci/fairsoft/fairmq_dev/lib/libboost_atomic.dylib                     /Users/alfaci/fairsoft/fairmq_dev/lib/libboost_log_setup.dylib                  /Users/alfaci/fairsoft/fairmq_dev/lib/libboost_serialization.dylib
/Users/alfaci/fairsoft/fairmq_dev/lib/libboost_chrono.dylib                     /Users/alfaci/fairsoft/fairmq_dev/lib/libboost_math_c99.dylib                   /Users/alfaci/fairsoft/fairmq_dev/lib/libboost_signals.dylib
/Users/alfaci/fairsoft/fairmq_dev/lib/libboost_container.dylib                  /Users/alfaci/fairsoft/fairmq_dev/lib/libboost_math_c99f.dylib                  /Users/alfaci/fairsoft/fairmq_dev/lib/libboost_stacktrace_addr2line.dylib
/Users/alfaci/fairsoft/fairmq_dev/lib/libboost_context.dylib                    /Users/alfaci/fairsoft/fairmq_dev/lib/libboost_math_c99l.dylib                  /Users/alfaci/fairsoft/fairmq_dev/lib/libboost_stacktrace_basic.dylib
/Users/alfaci/fairsoft/fairmq_dev/lib/libboost_contract.dylib                   /Users/alfaci/fairsoft/fairmq_dev/lib/libboost_math_tr1.dylib                   /Users/alfaci/fairsoft/fairmq_dev/lib/libboost_stacktrace_noop.dylib
/Users/alfaci/fairsoft/fairmq_dev/lib/libboost_coroutine.dylib                  /Users/alfaci/fairsoft/fairmq_dev/lib/libboost_math_tr1f.dylib                  /Users/alfaci/fairsoft/fairmq_dev/lib/libboost_system.dylib
/Users/alfaci/fairsoft/fairmq_dev/lib/libboost_date_time.dylib                  /Users/alfaci/fairsoft/fairmq_dev/lib/libboost_math_tr1l.dylib                  /Users/alfaci/fairsoft/fairmq_dev/lib/libboost_thread.dylib
/Users/alfaci/fairsoft/fairmq_dev/lib/libboost_fiber.dylib                      /Users/alfaci/fairsoft/fairmq_dev/lib/libboost_numpy27.dylib                    /Users/alfaci/fairsoft/fairmq_dev/lib/libboost_timer.dylib
/Users/alfaci/fairsoft/fairmq_dev/lib/libboost_filesystem.dylib                 /Users/alfaci/fairsoft/fairmq_dev/lib/libboost_prg_exec_monitor.dylib           /Users/alfaci/fairsoft/fairmq_dev/lib/libboost_type_erasure.dylib
/Users/alfaci/fairsoft/fairmq_dev/lib/libboost_graph.dylib                      /Users/alfaci/fairsoft/fairmq_dev/lib/libboost_program_options.dylib            /Users/alfaci/fairsoft/fairmq_dev/lib/libboost_unit_test_framework.dylib
/Users/alfaci/fairsoft/fairmq_dev/lib/libboost_iostreams.dylib                  /Users/alfaci/fairsoft/fairmq_dev/lib/libboost_python27.dylib                   /Users/alfaci/fairsoft/fairmq_dev/lib/libboost_wave.dylib
/Users/alfaci/fairsoft/fairmq_dev/lib/libboost_locale.dylib                     /Users/alfaci/fairsoft/fairmq_dev/lib/libboost_random.dylib                     /Users/alfaci/fairsoft/fairmq_dev/lib/libboost_wserialization.dylib
/Users/alfaci/fairsoft/fairmq_dev/lib/libboost_log.dylib                        /Users/alfaci/fairsoft/fairmq_dev/lib/libboost_regex.dylib
```

**Comment by AndreyLebedev** [comment] 2020-02-04 09:07
@dennisklein The error disappeared. I tried to reproduce it with different environments but I can't. Closing the issue.

**Comment by AndreyLebedev** [comment] 2020-02-04 13:46
I've looked again to this issue. The difference between my environments, which has an error and which doesn't have it, is the Boost installation. In the case of the error, I used Boost 1.70. My installation of Boost 1.70 doesn't contain `RPATH`:
```
otool -L libboost_program_options.dylib 
libboost_program_options.dylib:
	libboost_program_options.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
```

And installation of Boost 1.71 containes `RPATH`:
```
otool -L libboost_program_options.dylib
libboost_program_options.dylib:
	@rpath/libboost_program_options.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
```

In the second case, DYLD_LIBRARY_PATH is not required. Thus, everything works.

The issue is still valid for cases were Boost installed without `RPATH` or fully qualified path.

**Comment by dennisklein** [comment] 2020-02-04 18:54
I think we have done all that can be done. We are setting RPATH entries in the FairMQ and DDS executables to the Boost lib directories and we are setting now `DYLD_LIBRARY_PATH` with your patch from #236. If you have more ideas, I am all ears.

If the measure above are not enough I tend to declare this a bug of the boost installation procedure. They have to make sure the `LC_ID`, `LC_LOAD_DYLIB` and `LC_RPATH` entries in the boost libs are correct...

**Comment by AndreyLebedev** [comment] 2020-02-05 07:55
The issue is only relevant for `fair::mq::sdk::DDSEnv` and Boost installation without `RPATH`.
Since `FairSoft` installs Boost with fully qualified paths the issue is only relevant for custom Boost installations.
If you consider `RPATH` as a requirement for Boost installation please close the issue.

**Comment by dennisklein** [comment] 2020-02-05 08:04
> If you consider RPATH as a requirement for Boost installation please close the issue.

Let's say, it is not a requirements. What could we do? Check at compile time of FairMQ, if the Boost installation needs a LIBRARY_PATH and burn it into the DDSEnv code? Or is it the responsibility of the user or the package manager to setup the environment at runtime?

**Comment by dennisklein** [comment] 2020-02-05 08:05
Or should DDS burn such LIBRARY_PATH into its own executables already?

**Comment by AndreyLebedev** [comment] 2020-02-05 08:35
> Or should DDS burn such LIBRARY_PATH into its own executables already?

We are investigating this option already.

Another option is to source `DDS_env.sh` script before executing `dds-user-defaults` in the command string of `std::system`.

**Comment by dennisklein** [comment] 2020-02-05 08:47
> Another option is to source DDS_env.sh script

The idea of `sdk::DDSEnv` is that it is a C++ implementation of `DDS_env.sh` - except that it did not replicate the `LIBRARY_PATH` management up to now.

**Comment by dennisklein** [comment] 2020-02-05 09:03
I just realize this discussion is a duplicate of FairRootGroup/DDS#224. Points are already made there. 

The conclusion there was, to support non-RPATH-enabled boost installations, the user has to setup his environment e.g. by sourcing `DDS_env.sh` (just for the saks of LIBRARY_PATH) or other means (e.g. `module load boost`).

Regarding the non-LIBRARY_PATH aspects of `DDS_env.sh` we have the other issue. I believe they can be solved without a bash script.

**Comment by AnarManafov** [comment] 2020-02-05 09:16
@dennisklein , I think, the main point of this ticket is that fair::mq::sdk::DDSEnv makes a call to dds-user-defaults without setting up its environment. For a user, who has boost without rpath there is no way to work this case around. The API call will always fail. The other point, it is not critical, but still.

I think, it's a responsibility of the the API to make sure that if it makes an external call, it should also initialise a proper environment for this call.
I might be mistaking, but if you source DDS_env.sh or export library path in the same command set with dds-user-defaults. Then the call to dds-user-defaults will succeed.

What I do believe, we can't require from the user to have boost build with rpath. It's too much of the requirement.

BTW, why did you break DDS_env.sh on the set of calls in fair::mq::sdk::DDSEnv?
Does it not complicate the maintainability of the API?
Consider cases if DDS_env.sh get some changes.

**Comment by dennisklein** [comment] 2020-02-05 09:26
>  why did you break DDS_env.sh on the set of calls in fair::mq::sdk::DDSEnv?

Because I want to have the hardcoded `$HOME/.DDS` configurable.

> Consider cases if DDS_env.sh get some changes.

Thats understood: That is why I opened FairRootGroup/DDS#224 ...

> I think, it's a responsibility of the the API to make sure that if it makes an external call, it should also initialise a proper environment for this call.

Whats the difference between an API and an executable like `dds-user-defaults`? You are burdening the user with having to do perform an extra step, too, before your executables can work with a non-RPATH bokst installation... Currently, the only way to get the functionality of `dds-user-defaults` is through calling it. There is no C++ API for it, is there?

**Comment by dennisklein** [comment] 2020-02-05 09:31
> What I do believe, we can't require from the user to have boost build with rpath. It's too much of the requirement.

Why? You have an even harder requirement and officially only accept boost installations without icu support.

**Comment by AnarManafov** [comment] 2020-02-05 09:39
> Why? You have an even harder requirement and officially only accept boost installations without icu support.

We don't require boost without icu. 
We rather recommend users to avoid icu to reduce the size of libraries. But users are free to link against icu if they want.  http://dds.gsi.de/doc/3.0/requirements.html

>Currently, the only way to get the functionality of dds-user-defaults is through calling it. There is no C++ API for it, is there?

This makes sense. We will open the user defaults API for users.
But the origin point is still valid. Why can't you call dds env or ld_library_path before spawning "dds-user-defaults"?

Regarding FairRootGroup/DDS#224 .
DDS uses rpath for its own libs. As for the boost dependencies - the only dirty solution I see is to rewrite boost libs in dds with rpath. Honestly don't like this solution and usage of install_name_tool in general, but most probably will do.

**Comment by dennisklein** [comment] 2020-02-05 10:11
To summarize:

* If the user wants to use the FairMQ SDK C++ API against a non-RPATH-enabled, and non-system Boost installation, she should make sure her dynamic loader can find this Boost installation, e.g. by setting the necessary LD_LIBRARY_PATH or similar. (She may very well choose to accomplish that by sourcing `DDS_env.sh`.) Another example is Andrey's recent patch in #236. A third example would be to setup the custom Boost installation with environment modules.

* It is understood that the current implementation of `sdk::DDSEnv` is not future-proof.
   * FairRootGroup/DDS#224 opened the discussion on how to improve on that
   * and in addition opens the feature request to have the hardcoded `$HOME/.DDS` be user-configurable.

**Comment by AnarManafov** [comment] 2020-02-05 10:16
>If the user wants to use the FairMQ SDK C++ API against a non-RPATH-enabled, and non-system Boost installation, she should make sure her dynamic loader can find this Boost installation, e.g. by setting the necessary LD_LIBRARY_PATH or similar.

This is exactly the point of this ticket. On OSX users can't do that. When you make a system (shall) call to dds-user-defaults the user LD_LIBRARY_PATH is not propagated to the call: https://developer.apple.com/library/archive/documentation/Security/Conceptual/System_Integrity_Protection_Guide/RuntimeProtections/RuntimeProtections.html

**Comment by dennisklein** [comment] 2020-02-05 10:17
Then on macOS you cannot have a non-RPATH, non-system Boost installation, can you?

**Comment by AnarManafov** [comment] 2020-02-05 10:20
> Then on macOS you cannot have a non-RPATH, non-system Boost installation, can you?
Why not? Just source lib path on the same shell you make external calls.

**Comment by dennisklein** [comment] 2020-02-05 10:22
You just said this is not possible??

**Comment by dennisklein** [comment] 2020-02-05 10:25
Ok, lets make it easier. Obviously I am not getting your point. Can you provide the patch or a PR to accomplish what you mean?

**Comment by AnarManafov** [comment] 2020-02-05 10:28
> You just said this is not possible??

I don't think I ever said that. You probably misunderstood.
Look, the parent library paths are not propagated to the child environment. But children are free to set their own environment. What I meant, is that when you spawn an external process, it won't inherit lib paths from your process, but you can set its own environment.

~~~~
bash -c "export DYLD_LIBRARY_PATH=<...>; dds-user-default --help"
~~~~
or maybe something like 
~~~~
bash -c "source DDS_env.h; dds-user-default --help"
~~~~

**Comment by dennisklein** [comment] 2020-02-05 10:35
> `bash -c "export DYLD_LIBRARY_PATH=<...>; dds-user-default --help"`

According to the link you posted this will not work if `dds-user-default` is protected.

**Comment by AnarManafov** [comment] 2020-02-05 10:40
It works. The kernel purges only, so to say, the second level of inheritance.

**Comment by dennisklein** [comment] 2020-02-05 10:50
> It works. The kernel purges only, so to say, the second level of inheritance.

I am not convinced. Do you have a mac with SIP enabled? I would like to try this.

**Comment by AnarManafov** [comment] 2020-02-05 10:53
> Do you have a mac with SIP enabled? I would like to try this.

All macs by default are with SIP. One has to explicitly disable it and it's not that obvious, for regular users, how exactly.

**Comment by dennisklein** [comment] 2020-02-05 10:57
Let me check if Mohammad has disabled it - I thought so, could be wrong. I only have access to his witmac007 and demac016.

**Comment by dennisklein** [comment] 2020-02-05 11:10
```
demac016:~ alfaci$ csrutil status
System Integrity Protection status: enabled.
demac016:~ alfaci$ cat demo.sh
export DYLD_LIBRARY_PATH=asdf
env | grep ^DYLD_LIBRARY_PATH
demac016:~ alfaci$ bash demo.sh
demac016:~ alfaci$
```
```
alfaci at witmac007 in ~$ csrutil status
System Integrity Protection status: disabled.
alfaci at witmac007 in ~$ cat demo.sh
export DYLD_LIBRARY_PATH=asdf
env | grep ^DYLD_LIBRARY_PATH
alfaci at witmac007 in ~$ bash demo.sh
DYLD_LIBRARY_PATH=asdf
alfaci at witmac007 in ~$
alfaci at witmac007 in ~$ logout
```

**Comment by AnarManafov** [comment] 2020-02-05 11:31
~~~
anar@demac028 tmp % csrutil status
System Integrity Protection status: enabled.
anar@demac028 tmp % cat demo.sh 
#!/usr/bin/env bash

#export DYLD_LIBRARY_PATH=/Users/anar/DDS/3.1.9.g8950bb8/lib

/Users/anar/DDS/3.1.9.g8950bb8/bin/dds-user-defaults --help%                                                                                                                                                                                                                                                                                                         anar@demac028 tmp % ./demo.sh 
dyld: Library not loaded: libboost_program_options.dylib
  Referenced from: /Users/anar/DDS/3.1.9.g8950bb8/bin/dds-user-defaults
  Reason: image not found
./demo.sh: line 5: 98779 Abort trap: 6           /Users/anar/DDS/3.1.9.g8950bb8/bin/dds-user-defaults --help
anar@demac028 tmp % 
anar@demac028 tmp % 
anar@demac028 tmp % 
anar@demac028 tmp % cat demo.sh
#!/usr/bin/env bash

export DYLD_LIBRARY_PATH=/Users/anar/DDS/3.1.9.g8950bb8/lib

/Users/anar/DDS/3.1.9.g8950bb8/bin/dds-user-defaults --help%                                                                                                                                                                                                                                                                                                         anar@demac028 tmp % ./demo.sh  
Options:
  -h [ --help ]              Produce help message
  -v [ --version ]           Version information
  -V [ --verbose ]           Cause dds-user-defaults to be verbose in case of 
                             an error
  -p [ --path ]              Show DDS user defaults config file path
  -d [ --default ]           Generate a default DDS configuration file
  -c [ --config ] arg        DDS user defaults configuration file
  -s [ --session ] arg       DDS Session ID
  --ignore-default-sid       Ignore default DDS Session ID
  --key arg                  Get a value for the given key
  -f [ --force ]             If the destination file exists, remove it and 
                             create a new file, without prompting for 
                             confirmation
  --wrkpkg                   Show the full path of the worker package. The path
                             must be evaluated before use
  --wrkscript                Show the full path of the worker script. The path 
                             must be evaluated before use
  --rms-sandbox-dir          Show the full path of the RMS sandbox directory. 
                             It returns server.sandbox_dir if it is not empty, 
                             otherwise server.work_dir is returned. The path 
                             must be evaluated before use
  --user-env-script          Show the full path of user's environment script 
                             for workers (if present). The path must be 
                             evaluated before use
  --server-info-file         Show the full path of the DDS server info file. 
                             The path must be evaluated before use.
  --session-id-file          Show the full path of the session ID file of the 
                             local environment.
  --default-session-id       Show the current default session ID.
  --default-session-id-file  Show the full path of the default session ID file.
~~~

**Comment by dennisklein** [comment] 2020-02-05 12:29
I did some more tests: `dds-user-defaults` is not SIP-protected, `env` and `bash` are. That is why nesting with `bash`s or the demo with `env` filter out the `DYLD_LIBRARY_PATH`.

`std::system` which is used in `sdk::DDSEnv` spawns a `bash` and thus filters out the library paths from parents. So, I would propose to replace `std::system` with a more direct call of `dds-user-defaults` (without SIP-protected `bash` indirection) to support `DYLD_LIBRARY_PATH`s coming from the user's environment (also the ODC executables are not SIP-protected).

**Comment by dennisklein** [comment] 2020-02-05 12:33
https://support.apple.com/en-us/HT204899 SIP filters apparently only apply to programs in specific system directories by default.

**Comment by AnarManafov** [comment] 2020-02-05 12:36
@dennisklein , just for my info. What do you mean by
> I did some more tests: dds-user-defaults is not SIP-protected, env and bash are.

Does it mean we can build a SIP-protected executable like the "env" command?
I doubt it, as I've never heard about it. But it will be the ultimate solution for propagation of the lib path. Many apps suffer from SIP and using nasty workarounds.

**Comment by dennisklein** [comment] 2020-02-05 13:16
> Does it mean we can build a SIP-protected executable like the "env" command?

The flag is stored directories and files in an extended attribute with key `com.apple.rootless`:
```
demac016:~ alfaci$ ls -le@d /bin /usr /usr/local
drwxr-xr-x@ 38 root  wheel  1216 Nov 21 09:09 /bin
        com.apple.rootless         0 
drwxr-xr-x@ 11 root  wheel   352 Oct 10  2017 /usr
        com.apple.rootless         0 
drwxr-xr-x  16 root  wheel   512 Sep  6  2018 /usr/local
```

But I could not set it on my own files:
```
demac016:~ alfaci$ chflags nouchg,noschg demo/DDS/dds_install/bin/dds-user-defaults
demac016:~ alfaci$ xattr -w com.apple.rootless 0 demo/DDS/dds_install/bin/dds-user-defaults
xattr: [Errno 1] Operation not permitted: 'demo/DDS/dds_install/bin/dds-user-defaults'
```

So, I guess, it is not intended to be used except by Apple. A quick google search gives me the impression that this xattr may be mutable in safe boot mode as root.

Btw, there seems to be `csrutil enable –without fs` which only disables those SIP-filters on files but does not switch other unrelated SIP features.
```

**Comment by dennisklein** [comment] 2020-02-05 14:38
Summary take 2:

* If the user wants to use the FairMQ SDK C++ API against a non-RPATH-enabled, and non-system Boost installation, she should make sure her dynamic loader can find this Boost installation, e.g. by setting the necessary LD_LIBRARY_PATH or similar. (She may very well choose to accomplish that by sourcing DDS_env.sh. Another example is Andrey's recent patch in #236. A third example would be to setup the custom Boost installation with environment modules.)
=> This is currently prohibited on SIP-enabled systems because we use `std::system` which spawns a system `bash` which filters out `DYLD_LIBRARY_PATH`. Repurposing this issue to track implementation of a more direct call to `dds-user-defaults` without shell indirection.
=> Since we know at least about one valid Boost installation at build time, append (! to not override user's choice) this path into `DYLD_LIBRARY_PATH` before calling `dds-user-defaults`

* It is understood that the current implementation of sdk::DDSEnv is not future-proof.
   *FairRootGroup/DDS#224 opened the discussion on how to improve on that
   * and in addition opens the feature request to have the hardcoded $HOME/.DDS be user-configurable.
=> Once supported in DDS, we can replace calling of the executable `dds-user-defaults` with the appropriate C++ API calls.

**Closed** 2020-02-17 18:50 UTC
Labels: enhancement
